version: '3.0'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: 1282240S
       MYSQL_DATABASE: mydb
       MYSQL_PASSWORD: 1282240S
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   accountownerapp:
     depends_on:
       - db
     image: gregory82gr/accountowner:runtime
     build:
       context: .
     ports:
       - "8081:5000"

volumes:
    dbdata: